const BASE_URL = 'https://backend.ingeniebrios.work.gd';

const API_CONFIG = {
    AUTH_SERVICE: BASE_URL,
    CONCERT_SERVICE: BASE_URL,
    VENUE_SERVICE: BASE_URL,
    TICKET_SERVICE: BASE_URL,
    ORDER_SERVICE: BASE_URL,
    NOTIFICATION_SERVICE: BASE_URL,
};

export default API_CONFIG;